[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
script = 'script'
ffi = true
solc-version = '0.8.20'
optimizer = true
optimizer-runs = 200

[fmt]
line_length = 120

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
hoodi = "https://ethereum-hoodi-rpc.publicnode.com"

[etherscan]
hoodi = { key = "${ETHERSCAN_API_KEY}", chain = 560048, url = "https://hoodi.etherscan.io/api" }
